### ISSUE TITLE
Build warning MSB3246: Resolved file has a bad image

### ISSUE THREAD

**Issue by tomaskarban** [softwarehelden-com/Softwarehelden.Transactions.Oletx#15]
My project targets net6.0 and references nuget `Softwarehelden.Transactions.Oletx` version 1.3.0. AFAICT it works great, however I am getting a build warning. ILSpy does not report any problems loading the assembly (and its dependencies), so I am not sure what could be wrong with it.

Is the warning important? Is there a way to avoid it?

```
Resolved file has a bad image, no metadata, or is otherwise inaccessible. System.BadImageFormatException: Could not load file or assembly 'Softwarehelden.System.Security.Principal.Windows.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'Softwarehelden.System.Security.Principal.Windows.dll' ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.Build.Shared.AssemblyNameExtension.GetAssemblyNameEx(String path)
   at Microsoft.Build.Tasks.SystemState.GetAssemblyName(String path)
   at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName)
```

**Comment by tomaskarban** [comment]
I found out that the assembly `Softwarehelden.System.Security.Principal.Windows.dll` is built exclusively for x64, but my project is AnyCPU. After I switched my project to x64 the warning went away.

So, could this one assembly be built for AnyCPU like the rest of Softwarehelden assemblies, please?

**Comment by swh-cb** [comment]
Thank you for reporting the issue.

`Softwarehelden.System.Security.Principal.Windows` cannot be built for `AnyCPU` on .NET 6.0 because it contains unmanaged architecture specific code. .NET 6.0 provides the assembly `System.Security.Principal.Windows.dll` for x64 and x86 architecture on Windows:

x64: `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.5\System.Security.Principal.Windows.dll`
x86: `C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.5\System.Security.Principal.Windows.dll`

To avoid the build warning, the architecture specific assemblies can be packaged in NuGet under `runtimes/win-x64/lib/net6.0`. The `OletxCompatibilityLoadContext` must then use an `AssemblyDependencyResolver` to correctly load the architecture specific assemblies from the `runtimes` folder. As soon as I find time, I will implement it.

@KarbyCZ  Do you also need support for `win-x86`?

**Comment by tomaskarban** [comment]
I must say that even after I switched my project from AnyCPU to x64, I can see the warning occasionally (building in VS). It does not make any sense to me, it looks more like an MSBuild issue. Either way, I have no problem _running_ the code and it is working fine (even before I switched to x64 to get rid of the warning). So the problem seems to be purely _cosmetic_... I don't need x86.

**Comment by swh-cb** [comment]
Yes, you are right. If the application runs on `win-x64` or performs distributed MSSQL transactions without Oracle, the build warning will not affect you at runtime. `Softwarehelden.System.Security.Principal.Windows` is only required for distributed Oracle transactions using the unmanaged ODP.NET provider `Oracle.DataAccess`.

**Comment by swh-cb** [comment]
@KarbyCZ The new version 1.4.0 includes a fix for this build warning. The release also fixes an important issue to avoid connection pool corruption in the MSSQL data provider. Please check https://github.com/softwarehelden-com/Softwarehelden.Transactions.Oletx/issues/17 and https://github.com/dotnet/SqlClient/issues/1623. As a temporary workaround you can use the `MsSqlPatcher` patcher if your application explicitly aborts distributed transactions (e.g. `ROLLBACK TRANSACTION`) and connection pooling is enabled.
